const translations = {
    en: {
        'home': 'Home',
        'our_dna': 'Our DNA',
        'our_unique_advantage': 'Our unique advantage',
        'boost_your_business': 'Boost your business',
        'brand_tracking': 'Brand tracking',
        'brand_creation': 'Brand creation',
        'social_media_strategy': 'Social media strategy',
        'content_creation': 'Content creation',
        'web_creation': 'Web creation',
        'success_stories': 'Success stories',
        'our_green_ai': 'Green AI',
        'blog': 'Blog',
        'contact': 'Contact',
        'we_are_here': 'We\'re here for you',
        //// footer
        'footer_description': 'Your AI marketing agency that leads the digital revolution worldwide by merging artificial intelligence with human creativity',
        'pages': 'Pages',
        'home': 'Home',
        'services': 'Services',
        'our_dna': 'Our DNA',
        'ai_impact': 'AI impact',
        'address': 'Address',
        'address_details': 'Tunis, Tunisia <br>Paris, France',
        'get_estimate': 'Get free estimate',
        'placeholder_email': 'Your e-mail address',
        'footer_copyright': '© 2024 <a href="./" style="color: #00E37D;">Euklydia</a>, All Rights Reserved.',
        'terms_conditions': 'Terms & Conditions',
        'privacy_policy': 'Privacy policy',
        'contact_us': 'Contact us',
        'boost_brand_awareness': 'Boost brand awareness',
        'drive_sales': 'Drive sales',
        'engage_customers': 'Engage customers',
        'achieve_business_growth': 'Achieve business growth',
        'ai_digital_transformation_approach': 'Our <span class="pbmit-globalcolor">AI digital transformation</span> approach',
        'principles_we_live_by': '<span class="pbmit-globalcolor">Principles</span> we live by',
        'ai_driven_analytics': 'AI-driven analytics',
        'innovation': 'Innovation',
        'innovation_text': 'Our commitment to technology drives us to develop innovative solutions that address real customer challenges with new methods, products, and services.',
        'limitless_imagination': 'Limitless imagination',
        'creativity': 'Creativity',
        'creativity_text': 'At the core of our business, creativity and imagination drive our strategies, fostering innovative thinking. By recognizing their human essence, we craft unique solutions to stay ahead in a dynamic market.',
        'gender_neutral': 'Gender neutral',
        'diversity_inclusion': 'Diversity and inclusion',
        'diversity_inclusion_text': 'As proud tech advocates, gender equality is our reality. An inclusive culture fosters diversity, where everyone thrives, respecting differences.',
        'adaptability_to_change': 'Adaptability to change',
        'agility': 'Agility',
        'agility_text': 'Our superpower is agility, enabling us to effortlessly navigate the evolving business landscape.',
        'sustainable_tech': 'Sustainable tech',
        'eco_friendly': 'Eco-friendly',
        'eco_friendly_text': 'We eschew traditional data centers, leveraging transfer learning from industry leaders like Google and Meta to reduce our carbon footprint and align with sustainability.',
        'continuous_growth': 'Continuous growth',
        'lifetime_learning': 'Lifelong learning',
        'lifetime_learning_text': 'Our core policy, lifelong learning, motivates us, bridging generations. Seniors share wisdom, while younger members bring updates, ensuring continuous improvement and success.',
        'worldwide_talents_unified_vision': 'Worldwide talents, <span class="pbmit-globalcolor">unified vision</span>',
        'paragraph1': 'AI-driven marketing startup blending data and creativity to boost your business by crafting precise strategies and content creation.',
        'paragraph2': 'Your business benefits from our tailored strategies, precise targeting, and optimized funnels for effective marketing campaigns.',
        'paragraph3': 'We enhance brand tracking, predict customer behavior, and boost digital presence with our in-house AI.',
        'paragraph4': 'We reduce carbon footprint by using transfer learning for AI development, eliminating the need for data centers.',
        'paragraph5': 'We transform challenging situations into effective results for you.',
        'paragraph6': 'Your success drives us—reach out with any questions. We\'re here to help you thrive!',
        //// why us
        'traditional_marketing_is': 'Traditional marketing is <a class="pbmt-hover-text"><span class="hover-effect" data-translate="dead">dead</span>,</a>',
        'we_are_game': 'We are game <a class="pbmt-hover-text"><span class="hover-effect" data-translate="changers">changers</span></a>',

        'find_your_target_customers': 'Find your target customers',
        'find_your_target_customers_text': 'Our AI in-house algorithms revolutionize client targeting by analyzing vast datasets in real-time, enabling precise audience segmentation, personalized messaging, and dynamic campaign optimization, surpassing traditional methods\' accuracy and efficiency.',
        'empowering_social_media_engagement': 'Empowering social media engagement',
        'empowering_social_media_engagement_text': 'Our data-driven marketing revolutionizes social media reach and engagement by leveraging advanced algorithms to analyze user behavior, personalize content, and predict user reactions, overcoming information saturation and maintaining audience interest effectively compared to traditional methods.',
        'ai_for_competitive_advantage': 'AI for competitive advantage',
        'ai_for_competitive_advantage_text': 'Thanks to our AI technology, we can help you identify opportunities and threats more quickly, allowing you to respond swiftly to market changes and overcome competition.',
        'ai_brand_tracking_and_diagnosis': 'AI brand tracking and diagnosis',
        'ai_brand_tracking_and_diagnosis_text': 'Traditional marketing is time-consuming and susceptible to market changes, rendering insights outdated. Our in-house AI swiftly analyzes vast data sets with high accuracy, overcoming these challenges.',
        'your_path_to_profitable_business': 'Your path to <a href="#" class="pbmt-hover-text"><span class="hover-effect" data-text="profitable business" style="color: #00e37d">profitable business</span></a>',
        'profitable_business': 'Profitable business',

        'cost_efficiency_title': 'Cost efficiency',
        'cost_efficiency_text': 'Our AI-driven strategies precisely target your marketing efforts, reducing wasteful spending and maximizing return on investment by focusing on what truly resonates with your audience.',
        'time_optimization_title': 'Time optimization',
        'time_optimization_text': 'Streamline your operations with AI that quickly identifies the most effective website layouts and social media strategies, significantly reducing the time required to refine your online presence and engage your audience.',
        'risk_mitigation_title': 'Risk mitigation',
        'risk_mitigation_text': 'Tailor your brand\'s communication effectively across different platforms with our AI-generated customer avatars, minimizing the risk of misaligned messaging and enhancing brand loyalty through personalized interactions.',
        'our_approach_to_boost_your_business': 'Our approach to <a href="#" class="pbmt-hover-text"><span class="hover-effect" data-text="boost your business" style="color: #00e37d">boost your business</span></a>',
        'boost_your_business': 'Boost your business',
        'our_approach_to_boost_your_business': 'Our approach to <a href="#" class="pbmt-hover-text"><span class="hover-effect" style="color: #00e37d">boost your business</span></a>',
        'boost_your_business': 'Boost your business',
        ///// services
        'brand_tracking_title': 'Brand tracking',
        'brand_tracking_description': 'With over 120 KPIs dedicated to brand tracking, our AI-driven solutions offer unparalleled insight into your brand\'s health, impact, and performance.',
        'brand_creation_title': 'Brand creation',
        'brand_creation_description': 'Crafting personalized brands through AI data analysis, we provide logo design, brand messaging, identity development, brand books, and print media solutions.',
        'social_media_strategy_title': 'Social media strategy',
        'social_media_strategy_description': 'We meticulously craft personalized social media strategies that resonate with your audience. By identifying optimal platforms and refining posting schedules, we ensure unparalleled engagement and growth.',
        'content_creation_title': 'Content creation',
        'content_creation_description': 'We specialize in crafting captivating social media content tailored to your audience, boosting reach, engagement, and conversion rates across platforms like LinkedIn, Facebook, and Instagram.',
        'web_creation_title': 'Web creation',
        'web_creation_description': 'We design user-friendly websites, craft personalized content, optimize UX/UI, and supercharge SEO with AI technology.',
        'explore': 'Explore',
        //// usecase 
        'opportunities_slogan': 'See how we turned obstacles into opportunities <br> with our AI solutions',

        'challenge_title': 'The challenge:',
        'challenge_description': 'The client, a multinational service company, faced significant challenges with their previous marketing agency, experiencing a daily decline in Facebook ROI and minimal engagement. Frustrated with the lack of effective strategies and innovative solutions, they sought a dependable partner to reverse the downward trend and enhance their online presence. The client discovered Euklydia AI Marketing Agency through a referral from a satisfied customer, hoping to find a solution to their pressing marketing issues.',
        'strategy_title': 'The strategy:',
        'strategy_description': 'This account urgently needed improvement. Utilizing our in-house AI, we analyzed engaging keywords, optimal posting times, and relevant topics. Our analysis enabled us to predict ad copy, campaign content, and strategy reactions, allowing us to develop a precise Facebook strategy tailored to the target audience. This involved optimizing match types, distinguishing brand from non-brand keywords, and pausing underperforming ads. With this new foundation, our team concentrated on boosting sales volume and maximizing efficiency. To further enhance user experience, we delivered a customized rebranding solution specifically designed for the target client’s needs.',
        'result_title': 'The result:',
        'result_description': 'In just two months, we achieved remarkable results. Revenue increased by 1.8%, reflecting significant growth. Our strategic Facebook overhaul boosted reach by 128.9%, while Instagram followers grew by 120.5% and Facebook followers by 65.7%. With the expansion to Instagram, regained trust, and a clearly defined brand persona, the client\'s business is now poised for continued success.',
        'facebook_reach': 'Facebook reach',
        'instagram_reach': 'Instagram reach',
        'facebook_visits': 'Facebook visits',
        'instagram_profile_visits': 'Instagram profile visits',
        'linkedin_title': 'LinkedIn:',
        'linkedin_slogan': 'Watch us turn challenges into brand awareness with our AI-driven LinkedIn strategy',
        'linkedin_challenge_title': 'The challenge:',
        'linkedin_challenge_description': 'The client faced significant challenges due to an improvised LinkedIn strategy. Relying heavily on collecting data through extensive interviews, this approach consumed a lot of time and resources, leading to increased costs. The lack of a structured strategy resulted in inconsistent outcomes, making it difficult to effectively engage with the target audience and optimize brand awareness efforts. This inefficiency hampered their ability to scale and achieve desired business growth.',
        'linkedin_strategy_title': 'The strategy:',
        'linkedin_strategy_description': 'Our team began with thorough research of the customer base, utilizing LinkedIn and third-party data to develop messaging concepts tailored to specific customer segments. We structured the account into tightly focused ad groups to obtain the cleanest data possible. Brand search campaigns featured brand-modified keyword groups. Our in-house AI correlated maximum reach and engagement with all possible features, allowing us to create a LinkedIn strategy precisely targeted to the desired customer.',
        'linkedin_result_title': 'The result:',
        'linkedin_result_description': 'The LinkedIn ROAS began to increase after the second month. Initially, with an 80% ROAS in Month 1, the client wasn\'t seeing a positive return but chose to continue investing. By Month 3, we achieved a break-even ROAS, enabling us to scale up spending and gather the necessary data for more complex optimizations. From there, results skyrocketed. By Month 9, we achieved a robust 550% ROAS, transforming LinkedIn into a revenue-generating, ROI-positive channel.',
        // ia impact...
        'hero_subtitle': 'Euklydia',
        'hero_title': 'Green tech',
        'hero_description': 'At Euklydia, we champion a future where AI and ecology go hand-in-hand. Our commitment transcends the basic reduction of data\'s environmental toll, we embrace a holistic approach to sustainability that integrates cutting-edge technologies with eco-conscious practices.',
        'hero_link1': 'Green',
        'hero_link2': 'Sustainable',
        'hero_link3': 'Solutions',
        'rd_title': 'Research & development',
        'vision_title': 'Our vision for a greener AI',
        'vision_description': 'At Eyklydia, we utilize transfer learning and federated learning methods to handle large volumes of data in real-time, effectively reducing carbon emissions while promoting sustainable innovation instead of data center. Transfer learning leverages pre-trained models, minimizing the need for extensive computations and energy-intensive training processes. Federated learning decentralizes data processing, allowing for collaborative model training across multiple devices without centralizing data in energy-consuming data centers. This approach not only reduces energy consumption but also enhances privacy and security by keeping data localized. As a result, our innovative approach aligns with our commitment to eco-friendly practices while driving sustainable innovation in the energy transition.',
        'service1_title': 'GreenGenius',
        'service1_description': 'This technology guarantees that our offerings are sustainable, propelling your company to the forefront of eco-responsible innovation.',
        'service2_title': 'EcoOptiMind',
        'service2_description': 'Strategic decision-making with a green core. This sophisticated algorithm embeds sustainability into every facet of decision-making, enhancing the process.',
        'service3_title': 'INvestGenius',
        'service3_description': 'Investing sustainably with optimal returns. By minimizing resource use and targeting opportunities precisely, this ensures our offerings are sustainable.',
        'read_more': 'Read more',
        // Blog
        'page_title': 'Fuel your curiosity',
        'blog_intro': 'Your source for inspiration and knowledge',
        'date': 'June 1, 2024',
        'article1_title': '10 Major digital marketing trends to follow in 2024',
        'article1_description': 'Discover the key developments set to shape this pivotal year. fermentum ullamcorper viverra laoreet Aliquam.',
        'read_more': 'Read more',

        // Article 1
        'article_title': '10 Major digital marketing trends to follow in 2024',
        'by_euklydia': 'By Euklydia',
        'date': '1 June 2024',
        'intro_paragraph': 'In the fast-paced digital world, web professions and marketing strategies are constantly evolving. The massive integration of AI into businesses heralds significant digital marketing trends for 2024. Discover the key developments set to shape this pivotal year.',
        'trend1_title': '1. The fusion of e-commerce and social media: The rise of social commerce',
        'trend1_description': 'Social commerce, the merger of social media and e-commerce, is transforming the shopping experience. Platforms like Instagram, Facebook, TikTok, and Pinterest are becoming true marketplaces. The integration of direct shopping tools simplifies the buying process, while brands leverage engaging content to drive social interaction and purchases. Benefits of social commerce: simplifies the buying process, increases conversion rates, and offers the opportunity to target a wider audience through the viral dynamics of social networks.',
        'trend2_title': '2. Artificial intelligence: Personalization in digital marketing',
        'trend2_description': 'AI, a valuable ally in digital marketing, offers unparalleled analysis and prediction capabilities. In 2024, its growing use will anticipate consumer needs, enabling ultra-targeted campaigns. With AI, companies can process massive data volumes, predict user desires, and offer highly personalized experiences. Applications of AI: behavioral analysis, trend predictions, and personalized marketing campaigns.',
        'trend3_title': '3. Augmented reality: Transforming customer experience',
        'trend3_description': 'Augmented reality (AR) revolutionizes customer engagement by enabling immersive experiences such as virtual try-ons or product visualizations in real environments. It establishes customizable interactions, bridging the gap between e-commerce and physical stores, and offers opportunities for memorable advertising campaigns. Applications of AR: virtual product trials, interactive ads, and virtual tours.',
        'trend4_title': '4. Interactive content to engage the community',
        'trend4_description': 'Interactive content like quizzes, polls, and 360° videos boosts engagement while providing insights into consumer behavior. Unlike passive content, interactive content encourages action, enhancing information retention and brand connection. Benefits of interactive content: long-lasting engagement, improved information retention, and valuable data for analysis and optimization.',
        'trend5_title': '5. Ethical and transparent influencer marketing',
        'trend5_description': 'In 2024, influencer marketing is refocusing on ethics and transparency to restore consumer trust. Collaborations must be sincere, based on shared values, and companies must adapt to better-regulated influencer marketing practices. Toward regulation in influencer marketing: ethics, transparency, and collaborations based on genuine affinities.',
        'trend6_title': '6. SEO optimization beyond keywords in 2024',
        'trend6_description': 'SEO importance extends beyond keywords, demanding a consistent and effective omnichannel presence. In 2024, SEO will encompass a global ecosystem, ensuring optimal visibility across various platforms and devices. Omnichannel SEO: consistent user experience, adaptation to mobile and voice searches, and uniform presence across all channels.',
        'trend7_title': '7. Inbound marketing and content marketing: A winning combo',
        'trend7_description': 'Inbound marketing, focused on attracting customers through relevant content, combined with content marketing, offers a complete customer journey. This customer-centric approach turns satisfied clients into brand ambassadors, enhancing loyalty and marketing efficiency. Synergy of inbound marketing and content marketing: relationship building, conversion funnel, and customer retention.',
        'trend8_title': '8. Big data and digital marketing: The targeting revolution',
        'trend8_description': 'Big data enables hyper-personalized targeting by analyzing prospect behaviors. Marketing campaigns, based on real data, offer relevant and engaging customer experiences, adjustable in real-time to maximize conversions. Strategic use of big data: personalized targeting, adjustable ads, and optimized purchase paths.',
        'trend9_title': '9. Mobile marketing and content: The association of digital giants',
        'trend9_description': 'Mobile marketing, essential with the proliferation of smartphones, offers personalization opportunities through data collection. Adapting content for mobile, short and impactful, allows for more relevant interaction, enhancing brand presence. Mobile marketing: mobile-friendly content, geolocation-based personalization, and increased engagement.',
        'trend10_title': '10. Marketing automation: Personalizing customer approach',
        'trend10_description': 'Marketing automation transforms customer interaction by automating tasks, offering a personalized experience. Combined with data analysis, it optimizes marketing campaigns, ensuring constant and relevant interaction with the audience. Benefits of marketing automation: task automation, advanced personalization, and integrated customer journey vision.',
        'conclusion_title': 'Conclusion:',
        'conclusion_description': 'In 2024, digital marketing evolves towards smarter, customer-centric strategies. Companies that incorporate these trends into their strategies will have the opportunity to stand out and build lasting relationships with their customers. Adaptability and innovation remain essential to stay competitive in an ever-changing landscape.',
        // contact...
        'get_in_touch': 'Get in touch',
        'elevate_brand': 'Elevate your brand with Euklydia',
        'contact_intro': 'Feel free to reach out to us <br> we\'re just a message away and ready to assist you with your needs!',
        'placeholder_first_name': 'Your first name',
        'placeholder_last_name': 'Your last name',
        'placeholder_email': 'Your email',
        'placeholder_company': 'Company',
        'placeholder_message': 'Message here..',
        'send_now': 'Send now',
        'address': 'Address',
        'address_details': 'Tunis, Tunisia <br>Paris, France',
        'email': 'E-mail',
        'call_us': 'Call us',
        'hiring': 'Hiring',
        'join_team': 'Be part of our team',
        'hiring_intro': 'If you are passionate, talented, and looking for a place where you can grow your career, we want to hear from you!',
        'placeholder_field': 'Field',
        ///brand
        'brand_creation_title': 'Brand creation',
        'current_problem': 'Current problem:',
        'problem_title_brand': 'Battling to maintain brand coherence amid rapid market changes?',
        'problem_description_brand': "Ensuring coherence between brand's logo, identity guidelines and your target customer requires ongoing monitoring adaptation to evolving consumer preferences and market dynamics. <br> This needs to keep an eye on all market evolving elements that could be very complicated to analyze manually in short order.",
        'time': 'Time',
        'money': 'Money',
        'brand_identity': 'Brand’s identity',
        'benefits': 'Benefits:',
        'customized_creativity': 'Customized creativity.',
        'increased_audience_resonance': 'Increased audience resonance.',
        'enhanced_design_alignment': 'Enhanced design alignment.',
        'streamlined_design_efficiency': 'Streamlined design efficiency.',
        'our_solution': 'Our solution',
        'solution_title': 'When targeted design <small>insights</small> meet custom <small>creativity</small>',
        'solution_description': 'Through our machine learning algorithms, we can identify patterns and correlations between different design elements, color schemes, and visual aesthetics that resonate with target audiences. <br><br> Our creative team adds an extra layer of creativity to make every customer special.',
/// tracking

        'brand_tracking': 'Brand tracking',
        'current_problem': 'Current problem:',
        'problem_title': 'Is market opacity clouding your strategy?',
        'problem_description': 'Current analog brand diagnosis solutions are costly in terms of both budget and time, lacking targeted and personalized strategic development, agility, and adaptability, resulting in inflexibility to rework, along with market opacity. Moreover, analogic brand tracking and diagnosis processes are time-consuming and subject to market changes, potentially rendering insights outdated by the time they are completed.',
        'time': 'Time',
        'money': 'Money',
        'benefits': 'Benefits:',
        'actionnable_insights': 'Actionnable insights.',
        'enhance_competitive_edge': 'Enhance your competitive edge.',
        'real_time_performance': 'Real time improved brand performance.',
        'increase_consumer_satisfaction': 'Increase consumer satisfaction.',
        'our_solution': 'Our solution',
        'solution_title': 'Unlock <small>insights</small> and adaptability for sharper <small>brand strategy</small>',
        'solution_description': 'Thanks to our in-house developed AI algorithm we can analyze vast data sets encompassing customer feedback, social media interactions, website traffic, and sales data to conduct your brand diagnostics. <br> <br>Our AI algorithms measure brand awareness, sentiment, and competitive analysis, providing insights into strengths, weaknesses, and opportunities for improvement. By tracking customer engagement metrics, assessing brand loyalty, and using predictive analytics, <br> <br> we can personalize your marketing efforts, optimize strategies, and enhance your competitive edge in the marketplace, leading to improved brand performance and consumer satisfaction.',
        'capitalize_opportunities': 'Capitalize on opportunities',
        'monitoring_brand': 'Monitoring brand',
        'understand_perception': 'Understand consumer perception',

/// social media 

        'social_media_strategy': 'Social media strategy',
        'current_problem': 'Current problem:',
        'problem_title_social_media': 'Frustrated by social media complexity and declining visibility?',
        'problem_description_social_media': 'Firstly, the ever-changing algorithms and features of platforms like Facebook, Instagram, and Twitter make it difficult for marketers to maintain consistent visibility and engagement with their target audience. <br>Moreover, the saturation of content on these platforms has led to decreased organic reach, requiring businesses to invest more in paid advertising to reach their desired audience effectively. Additionally, the rise of influencer marketing has introduced complexities in identifying authentic influencers and measuring the ROI of influencer partnerships. <br><br>Furthermore, the increasing importance of customer engagement and community building requires businesses to constantly monitor and respond to customer feedback and inquiries in a timely manner.',
        'revenue': 'Revenue',
        'cost': 'Cost',
        'social_media_repeat': 'Social media',
        'benefits': 'Benefits:',
        'improved_engagement': 'Improved engagement.',
        'personalized_communication': 'Personalized communication.',
        'increased_visibility': 'Increased visibility.',
        'higher_conversion_rates': 'Higher conversion rates.',
        'our_solution': 'Our solution',
        'solution_title_social_media': 'Boost your <small>social media</small> impact with <small>AI-driven</small> personalization',
        'solution_description_social_media': 'Our in-house developed AI strengthens consumer engagement with social media by analyzing user interactions with ads, refining strategies, and enhancing overall user experience through personalized messaging and optimized ad usability. <br><br>Analyzing huge amounts of data such as ad copy, comments, post type, vocabulary, and interaction allow us to create targeted messages that allow the customer to identify himself, which increases our visibility and conversion on meta platforms and LinkedIn.',

        // content creation
        'content_creation': 'Content creation',
        'current_problem': 'Current problem:',
        'problem_title_content_creation': 'Frustrated by content creation complexity and declining impact?',
        'problem_description_content_creation': 'Firstly, the ever-evolving standards and trends in content creation make it challenging for creators to consistently produce content that resonates with their audience. The need to stay updated with the latest formats, tools, and platforms can be overwhelming. <br>Moreover, the oversaturation of content across various media has led to a decline in audience engagement. This makes it harder for creators to stand out and capture the attention of their target audience without investing heavily in marketing and promotion. <br>Additionally, the rise of new content types, such as short-form videos and interactive media, introduces complexities in content strategy and production. Creators must continuously innovate and adapt to new formats to remain relevant.',
        'time': 'Time',
        'money': 'Money',
        'content_creation_repeat': 'Content creation',
        'benefits': 'Benefits:',
        'streamlined_content_strategy': 'Streamlined content strategy.',
        'efficient_production_process': 'Efficient production process.',
        'audience_centric_messaging': 'Audience-centric messaging.',
        'increased_content_impact': 'Increased content impact.',
        'our_solution': 'Our solution',
        'solution_title_content_creation': 'Revolutionize content creation with AI-driven innovation',
        'solution_description_content_creation': 'Our in-house developed AI transforms content creation by analyzing user interactions, optimizing strategies, and enhancing overall user experience through personalized content and streamlined production processes. <br><br>By analyzing vast amounts of data such as content type, comments, vocabulary, and engagement metrics, we craft targeted content that resonates with your audience. This approach boosts visibility and engagement across various platforms, leading to increased conversions and a stronger online presence. <br><br>Through AI-driven insights, we help you stay ahead of trends, adapt to changing standards, and continuously produce high-quality, impactful content.',

        // web creation
        'web_creation': 'Web creation',
        'current_problem': 'Current problem:',
        'problem_title_web_creation': 'Lost visitors and low conversions: Is your website design to blame?',
        'problem_description_web_creation': 'Firstly, unengaging content can discourage users from exploring further, leading to high bounce rates. <br><br> Secondly, poor information hierarchy may cause users to feel lost if crucial details are not highlighted or easily accessible. Additionally, complex forms can deter users from providing information, thereby reducing conversions. <br><br>Moreover, websites lacking optimization for search engines struggle to attract organic traffic, limiting visibility and effectiveness.',
        'connecting_with_target_customers': 'Connecting with your target customers',
        'benefits': 'Benefits:',
        'seo_optimization': 'SEO optimization',
        'enhanced_navigation': 'Enhanced navigation',
        'higher_conversion_rates': 'Higher conversion rates',
        'increased_engagement': 'Increased engagement',
        'our_solution': 'Our solution',
        'solution_title_web_creation': 'Boost your website\'s user experience and SEO with advanced AI and NLP analysis',
        'solution_description_web_creation': 'By analyzing user behavior with AI on the website, we can identify common navigation patterns and recommend the most intuitive and effective navigation. <br><br>LLM and NLP can assist in optimizing the content and structure of the site to enhance its ranking in search engines by identifying relevant keywords, optimizing meta tags, and recommending improvements. <br><br>This process is known as search engine optimization (SEO).'
    },
    fr: {
        'address': 'Adresse',
        'email': 'E-mail',
        'get_subscribed': 'Abonnez-vous!',
        'enter_email': 'Entrez votre e-mail',

        'home': 'Accueil',
        'our_dna': 'Notre ADN',
        'our_unique_advantage': 'Avantage unique',
        'boost_your_business': 'Booster votre activité',
        'brand_tracking': 'Suivi de marque',
        'brand_creation': 'Création de marque',
        'social_media_strategy': 'Stratégie réseaux sociaux',
        'content_creation': 'Création de contenu',
        'web_creation': 'Création web',
        'success_stories': 'Récits inspirants',
        'our_green_ai': 'IA verte',
        'blog': 'Blog',
        'contact': 'Contact',
        'footer_description': 'Votre agence de marketing IA qui mène la révolution numérique dans le monde entier en fusionnant l\'intelligence artificielle avec la créativité humaine',
        'pages': 'Pages',
        'home': 'Accueil',
        'services': 'Services',
        'our_dna': 'Notre ADN',
        'ai_impact': 'Impact de l\'IA',
        'address': 'Adresse',
        'address_details': 'Tunis, Tunisie <br>Paris, France',
        'get_estimate': 'Obtenez un devis gratuit',
        'placeholder_email': 'Votre adresse e-mail',
        'footer_copyright': '© 2024 <a href="./" style="color: #00E37D;">Euklydia</a>, Tous droits réservés.',
        'terms_conditions': 'Conditions générales',
        'privacy_policy': 'Politique de confidentialité',
        'contact_us': 'Contactez-nous',
        'we_are_here': 'Contactez-nous',
        'boost_brand_awareness': 'Accroître la notoriété de la marque',
        'drive_sales': 'Stimuler les ventes',
        'engage_customers': 'Engager les clients',
        'achieve_business_growth': 'Atteindre la croissance des affaires',
        'ai_digital_transformation_approach': 'Notre <span class="pbmit-globalcolor">approche de transformation numérique</span> par l\'IA',
        'principles_we_live_by': '<span class="pbmit-globalcolor">Les principes</span> qui nous guident',
        'ai_driven_analytics': 'Analyses pilotées par l\'IA',
        'innovation': 'Innovation',
        'innovation_text': 'Notre engagement envers la technologie nous pousse à développer des solutions innovantes répondant aux véritables défis des clients avec de nouvelles méthodes, produits et services.',
        'limitless_imagination': 'Imagination illimitée',
        'creativity': 'Créativité',
        'creativity_text': 'Au cœur de notre entreprise, la créativité et l\'imagination propulsent nos stratégies, favorisant la réflexion innovante. En reconnaissant leur essence humaine, nous élaborons des solutions uniques pour rester en avance dans un marché dynamique.',
        'gender_neutral': 'Neutre en termes de genre',
        'diversity_inclusion': 'Diversité et inclusion',
        'diversity_inclusion_text': 'En tant que fervents défenseurs de la technologie, l\'égalité des sexes est notre réalité. Une culture inclusive favorise la diversité, où chacun prospère en respectant les différences.',
        'adaptability_to_change': 'Adaptabilité au changement',
        'agility': 'Agilité',
        'agility_text': 'Notre superpuissance est l\'agilité, nous permettant de naviguer sans effort dans un paysage commercial en constante évolution.',
        'sustainable_tech': 'Technologie durable',
        'eco_friendly': 'Écologique',
        'eco_friendly_text': 'Nous évitons les centres de données traditionnels, en utilisant le transfert d\'apprentissage des leaders de l\'industrie comme Google et Meta pour réduire notre empreinte carbone et aligner notre durabilité.',
        'continuous_growth': 'Croissance continue',
        'lifetime_learning': 'Apprentissage à vie',
        'lifetime_learning_text': 'Notre politique de base, l\'apprentissage tout au long de la vie, nous motive, reliant les générations. Les aînés partagent leur sagesse, tandis que les plus jeunes apportent des mises à jour, assurant une amélioration continue et le succès.',
        'worldwide_talents_unified_vision': 'Talents mondiaux, <span class="pbmit-globalcolor">vision unifiée</span>',
        'paragraph1': 'Startup de marketing pilotée par l\'IA, mêlant données et créativité pour dynamiser votre entreprise en élaborant des stratégies précises et en créant du contenu créatif et adapté.',
        'paragraph2': 'Votre entreprise bénéficie de nos stratégies sur mesure, de notre ciblage précis et de nos entonnoirs optimisés pour des campagnes marketing efficaces.',
        'paragraph3': 'Nous améliorons le suivi de la marque, prévoyons le comportement des clients et renforçons la présence numérique avec notre IA interne.',
        'paragraph4': 'Nous réduisons notre empreinte carbone en utilisant le transfert d\'apprentissage pour le développement de l\'IA, éliminant ainsi le besoin de centres de données.',
        'paragraph5': 'Nous transformons des situations difficiles en résultats efficaces pour vous.',
        'paragraph6': 'Votre succès nous motive, contactez-nous pour toute question. Nous sommes là pour vous aider à réussir!',

//// why us

'traditional_marketing_is': 'Le marketing traditionnel est <a class="pbmt-hover-text"><span class="hover-effect" data-translate="dead">mort</span>,</a>',
'we_are_game': 'Nous sommes des <a class="pbmt-hover-text"><span class="hover-effect" data-translate="changers">innovateurs</span></a>',

'find_your_target_customers': 'Trouvez vos clients cibles',
        'find_your_target_customers_text': 'Nos algorithmes internes d\'IA révolutionnent le ciblage des clients en analysant d\'énormes ensembles de données en temps réel, permettant une segmentation précise de l\'audience, des messages personnalisés et une optimisation dynamique des campagnes, surpassant ainsi la précision et l\'efficacité des méthodes traditionnelles.',
        'empowering_social_media_engagement': 'Favoriser l\'engagement sur les réseaux sociaux',
        'empowering_social_media_engagement_text': 'Notre marketing basé sur les données révolutionne la portée et l\'engagement sur les réseaux sociaux en utilisant des algorithmes avancés pour analyser le comportement des utilisateurs, personnaliser le contenu et prédire les réactions des utilisateurs, surmontant ainsi la saturation d\'informations et maintenant l\'intérêt du public de manière plus efficace que les méthodes traditionnelles.',
        'ai_for_competitive_advantage': 'IA pour un avantage concurrentiel',
        'ai_for_competitive_advantage_text': 'Grâce à notre technologie d\'IA, nous pouvons vous aider à identifier les opportunités et les menaces plus rapidement, vous permettant de réagir rapidement aux changements du marché et de surmonter la concurrence.',
        'ai_brand_tracking_and_diagnosis': 'Suivi et diagnostic de la marque par IA',
        'ai_brand_tracking_and_diagnosis_text': 'Le marketing traditionnel prend du temps et est sensible aux changements du marché, rendant les insights obsolètes. Notre IA interne analyse rapidement de vastes ensembles de données avec une grande précision, surmontant ces défis.',
        'your_path_to_profitable_business': 'Votre chemin vers un <a href="#" class="pbmt-hover-text"><span class="hover-effect" data-text="business rentable" style="color: #00e37d">business rentable</span></a>',

        'cost_efficiency_title': 'Efficacité des coûts',
        'cost_efficiency_text': 'Nos stratégies pilotées par l\'IA ciblent précisément vos efforts de marketing, réduisant les dépenses inutiles et maximisant le retour sur investissement en se concentrant sur ce qui résonne vraiment avec votre audience.',
        'time_optimization_title': 'Optimisation du temps',
        'time_optimization_text': 'Rationalisez vos opérations avec l\'IA qui identifie rapidement les mises en page de sites web et les stratégies de médias sociaux les plus efficaces, réduisant considérablement le temps nécessaire pour affiner votre présence en ligne et engager votre public.',
        'risk_mitigation_title': 'Atténuation des risques',
        'risk_mitigation_text': 'Adaptez efficacement la communication de votre marque sur différentes plateformes avec nos avatars clients générés par IA, minimisant le risque de messages mal alignés et renforçant la fidélité à la marque grâce à des interactions personnalisées.',
        'our_approach_to_boost_your_business': 'Notre approche pour <a href="#" class="pbmt-hover-text"><span class="hover-effect" data-text="booster votre activité" style="color: #00e37d">booster votre activité</span></a>',
        'boost_your_business': 'Booster votre activité',
        'our_approach_to_boost_your_business': 'Notre approche pour <a href="#" class="pbmt-hover-text"><span class="hover-effect" style="color: #00e37d">booster votre activité</span></a>',
        'boost_your_business': 'Booster votre activité',
        
        ////services :
        'brand_tracking_title': 'Suivi de marque',
        'brand_tracking_description': 'Avec plus de 120 indicateurs dédiés au suivi de marque, nos solutions pilotées par IA offrent une vision inégalée de la santé, de l\'impact et des performances de votre marque.',
        'brand_creation_title': 'Création de marque',
        'brand_creation_description': 'En créant des marques personnalisées grâce à l\'analyse des données par IA, nous fournissons la conception de logos, la communication de marque, le développement de l\'identité, les livres de marque et les solutions de médias imprimés.',
        'social_media_strategy_title': 'Stratégie réseaux sociaux',
        'social_media_strategy_description': 'Nous élaborons méticuleusement des stratégies de réseaux sociaux personnalisées qui résonnent avec votre audience. En identifiant les plateformes optimales et en affinant les horaires de publication, nous garantissons un engagement et une croissance inégalés.',
        'content_creation_title': 'Création de contenu',
        'content_creation_description': 'Nous sommes spécialisés dans la création de contenus captivants pour les réseaux sociaux, adaptés à votre audience, augmentant la portée, l\'engagement et les taux de conversion sur des plateformes telles que LinkedIn, Facebook et Instagram.',
        'web_creation_title': 'Création web',
        'web_creation_description': 'Nous concevons des sites web conviviaux, créons des contenus personnalisés, optimisons l\'UX/UI et améliorons le référencement avec la technologie IA.',
        'explore': 'Explorer',
///// usecase
'opportunities_slogan': 'Voyez comment nous avons transformé les obstacles en opportunités <br> grâce à nos solutions d\'IA',

'challenge_title': 'Le défi:',
'challenge_description': 'Le client, une entreprise de services multinationale, a rencontré des défis importants avec son agence de marketing précédente, subissant une baisse quotidienne du ROI sur Facebook et un engagement minimal. Frustré par l\'absence de stratégies efficaces et de solutions innovantes, il a cherché un partenaire fiable pour inverser la tendance et améliorer sa présence en ligne. Le client a découvert l\'agence Euklydia AI Marketing par le biais d\'une recommandation d\'un client satisfait, espérant trouver une solution à ses problèmes marketing urgents.',
'strategy_title': 'La stratégie:',
'strategy_description': 'Ce compte nécessitait une amélioration urgente. En utilisant notre IA interne, nous avons analysé des mots-clés engageants, des moments optimaux pour publier et des sujets pertinents. Notre analyse nous a permis de prédire les réactions aux textes publicitaires, au contenu des campagnes et aux stratégies, nous permettant de développer une stratégie Facebook précise adaptée au public cible. Cela impliquait l\'optimisation des types de correspondance, la distinction des mots-clés de marque des non-marques et la mise en pause des annonces sous-performantes. Avec cette nouvelle base, notre équipe s\'est concentrée sur l\'augmentation du volume des ventes et la maximisation de l\'efficacité. Pour améliorer encore l\'expérience utilisateur, nous avons livré une solution de rebranding personnalisée spécialement conçue pour les besoins du client cible.',
'result_title': 'Le résultat:',
'result_description': 'En seulement deux mois, nous avons obtenu des résultats remarquables. Le chiffre d\'affaires a augmenté de 1,8 %, reflétant une croissance significative. Notre refonte stratégique de Facebook a boosté la portée de 128,9 %, tandis que les abonnés Instagram ont augmenté de 120,5 % et les abonnés Facebook de 65,7 %. Avec l\'expansion sur Instagram, la confiance retrouvée et une persona de marque clairement définie, l\'entreprise du client est désormais prête pour un succès continu.',
'facebook_reach': 'Reach Facebook',
'instagram_reach': 'Reach Instagram',
'facebook_visits': 'Visites Facebook',
'instagram_profile_visits': 'Visites de profil Instagram',
'linkedin_title': 'LinkedIn:',
'linkedin_slogan': 'Regardez-nous transformer les défis en notoriété de marque avec notre stratégie LinkedIn pilotée par l\'IA',
'linkedin_challenge_title': 'Le défi:',
'linkedin_challenge_description': 'Le client a rencontré des défis importants en raison d\'une stratégie LinkedIn improvisée. S\'appuyant fortement sur la collecte de données via des entretiens approfondis, cette approche consommait beaucoup de temps et de ressources, entraînant une augmentation des coûts. L\'absence d\'une stratégie structurée a conduit à des résultats incohérents, rendant difficile l\'engagement efficace avec le public cible et l\'optimisation des efforts de notoriété de marque. Cette inefficacité a entravé leur capacité à évoluer et à atteindre la croissance commerciale souhaitée.',
'linkedin_strategy_title': 'La stratégie:',
'linkedin_strategy_description': 'Notre équipe a commencé par une recherche approfondie de la base de clients, en utilisant LinkedIn et des données tierces pour développer des concepts de messages adaptés à des segments de clients spécifiques. Nous avons structuré le compte en groupes d\'annonces ciblés de manière étroite pour obtenir les données les plus propres possibles. Les campagnes de recherche de marque comportaient des groupes de mots-clés modifiés par marque. Notre IA interne a corrélé la portée et l\'engagement maximaux avec toutes les fonctionnalités possibles, nous permettant de créer une stratégie LinkedIn précisément ciblée sur le client souhaité.',
'linkedin_result_title': 'Le résultat:',
'linkedin_result_description': 'Le ROAS LinkedIn a commencé à augmenter après le deuxième mois. Initialement, avec un ROAS de 80 % au cours du premier mois, le client ne voyait pas un retour positif mais a choisi de continuer à investir. Au cours du troisième mois, nous avons atteint un ROAS à l\'équilibre, nous permettant d\'augmenter les dépenses et de collecter les données nécessaires pour des optimisations plus complexes. À partir de là, les résultats ont explosé. Au bout de neuf mois, nous avons atteint un ROAS robuste de 550 %, transformant LinkedIn en un canal générateur de revenus et positif en termes de ROI.',
        // ia impact...
        'hero_subtitle': 'Euklydia',
        'hero_title': 'Tech verte',
        'hero_description': 'Chez Euklydia, nous défendons un avenir où l\'IA et l\'écologie vont de pair. Notre engagement dépasse la simple réduction de l\'impact environnemental des données, nous adoptons une approche holistique de la durabilité qui intègre des technologies de pointe avec des pratiques éco-conscientes.',
        'hero_link1': 'Vert',
        'hero_link2': 'Durable',
        'hero_link3': 'Solutions',
        'rd_title': 'Recherche & développement',
        'vision_title': 'Notre vision pour une IA plus verte',
        'vision_description': 'Chez Eyklydia, nous utilisons des méthodes d\'apprentissage par transfert et d\'apprentissage fédéré pour traiter de grands volumes de données en temps réel, réduisant efficacement les émissions de carbone tout en favorisant l\'innovation durable au lieu du centre de données. L\'apprentissage par transfert exploite des modèles pré-entraînés, minimisant le besoin de calculs intensifs et de processus de formation énergivores. L\'apprentissage fédéré décentralise le traitement des données, permettant une formation collaborative de modèles sur plusieurs appareils sans centraliser les données dans des centres de données énergivores. Cette approche réduit non seulement la consommation d\'énergie, mais améliore également la confidentialité et la sécurité en gardant les données localisées. En conséquence, notre approche innovante s\'aligne sur notre engagement envers des pratiques éco-responsables tout en stimulant l\'innovation durable dans la transition énergétique.',
        'service1_title': 'GreenGenius',
        'service1_description': 'Cette technologie garantit que nos offres sont durables, propulsant votre entreprise à l\'avant-garde de l\'innovation écoresponsable avec nos solutions vertes.',
        'service2_title': 'EcoOptiMind',
        'service2_description': 'Prise de décision stratégique avec un cœur vert. Cet algorithme sophistiqué intègre la durabilité dans tous les aspects de la prise de décision, améliorant le processus.',
        'service3_title': 'INvestGenius',
        'service3_description': 'Investir de manière durable avec des rendements optimaux. En minimisant l\'utilisation des ressources et en ciblant précisément les opportunités, cela garantit que nos offres sont durables.',
        'read_more': 'En savoir plus',
//// blog
                 'page_title': 'Alimentez votre curiosité',
                'blog_intro': 'Votre source d\'inspiration et de connaissance',
                'date': '1er juin 2024',
                'article1_title': '10 grandes tendances du marketing digital à suivre en 2024',
                'article1_description': 'Découvrez les développements clés qui façonneront cette année charnière. fermentum ullamcorper viverra laoreet Aliquam.',
                'read_more': 'En savoir plus',
        
        // Article 1
        'article_title': '10 grandes tendances du marketing digital à suivre en 2024',
        'by_euklydia': 'Par Euklydia',
        'date': '1er juin 2024',
        'intro_paragraph': 'Dans le monde numérique en évolution rapide, les professions du web et les stratégies marketing évoluent constamment. L\'intégration massive de l\'IA dans les entreprises annonce des tendances significatives en marketing digital pour 2024. Découvrez les développements clés qui façonneront cette année charnière.',
        'trend1_title': '1. La fusion du e-commerce et des réseaux sociaux : L\'essor du commerce social',
        'trend1_description': 'Le commerce social, la fusion des réseaux sociaux et du e-commerce, transforme l\'expérience d\'achat. Les plateformes comme Instagram, Facebook, TikTok et Pinterest deviennent de véritables places de marché. L\'intégration d\'outils d\'achat direct simplifie le processus d\'achat, tandis que les marques exploitent du contenu engageant pour stimuler l\'interaction sociale et les achats. Avantages du commerce social : simplifie le processus d\'achat, augmente les taux de conversion et offre la possibilité de cibler un public plus large grâce à la dynamique virale des réseaux sociaux.',
        'trend2_title': '2. Intelligence artificielle : Personnalisation dans le marketing digital',
        'trend2_description': 'L\'IA, un allié précieux en marketing digital, offre des capacités d\'analyse et de prédiction inégalées. En 2024, son utilisation croissante permettra d\'anticiper les besoins des consommateurs, permettant des campagnes ultra-ciblées. Avec l\'IA, les entreprises peuvent traiter des volumes massifs de données, prédire les désirs des utilisateurs et offrir des expériences hautement personnalisées. Applications de l\'IA : analyse comportementale, prédictions de tendances et campagnes marketing personnalisées.',
        'trend3_title': '3. Réalité augmentée : Transformer l\'expérience client',
        'trend3_description': 'La réalité augmentée (RA) révolutionne l\'engagement client en permettant des expériences immersives telles que les essayages virtuels ou les visualisations de produits dans des environnements réels. Elle établit des interactions personnalisables, comblant le fossé entre le e-commerce et les magasins physiques, et offre des opportunités pour des campagnes publicitaires mémorables. Applications de la RA : essais virtuels de produits, publicités interactives et visites virtuelles.',
        'trend4_title': '4. Contenu interactif pour engager la communauté',
        'trend4_description': 'Le contenu interactif comme les quiz, les sondages et les vidéos à 360° augmentent l\'engagement tout en fournissant des insights sur le comportement des consommateurs. Contrairement au contenu passif, le contenu interactif encourage l\'action, améliorant la rétention d\'information et la connexion à la marque. Avantages du contenu interactif : engagement durable, meilleure rétention d\'information et données précieuses pour l\'analyse et l\'optimisation.',
        'trend5_title': '5. Marketing d\'influence éthique et transparent',
        'trend5_description': 'En 2024, le marketing d\'influence se recentre sur l\'éthique et la transparence pour restaurer la confiance des consommateurs. Les collaborations doivent être sincères, basées sur des valeurs partagées, et les entreprises doivent s\'adapter à des pratiques de marketing d\'influence mieux régulées. Vers une régulation du marketing d\'influence : éthique, transparence et collaborations basées sur des affinités authentiques.',
        'trend6_title': '6. Optimisation SEO au-delà des mots-clés en 2024',
        'trend6_description': 'L\'importance du SEO s\'étend au-delà des mots-clés, nécessitant une présence omnicanal cohérente et efficace. En 2024, le SEO englobera un écosystème global, garantissant une visibilité optimale sur diverses plateformes et appareils. SEO omnicanal : expérience utilisateur cohérente, adaptation aux recherches mobiles et vocales, et présence uniforme sur tous les canaux.',
        'trend7_title': '7. Inbound marketing et content marketing : Un duo gagnant',
        'trend7_description': 'L\'inbound marketing, axé sur l\'attraction des clients grâce à du contenu pertinent, combiné au content marketing, offre un parcours client complet. Cette approche centrée sur le client transforme les clients satisfaits en ambassadeurs de la marque, renforçant la fidélité et l\'efficacité marketing. Synergie de l\'inbound marketing et du content marketing : construction de relations, entonnoir de conversion et fidélisation des clients.',
        'trend8_title': '8. Big data et marketing digital : La révolution du ciblage',
        'trend8_description': 'Le big data permet un ciblage hyper-personnalisé en analysant les comportements des prospects. Les campagnes marketing, basées sur des données réelles, offrent des expériences clients pertinentes et engageantes, ajustables en temps réel pour maximiser les conversions. Utilisation stratégique du big data : ciblage personnalisé, publicités ajustables et parcours d\'achat optimisés.',
        'trend9_title': '9. Marketing mobile et contenu : L\'association des géants du numérique',
        'trend9_description': 'Le marketing mobile, essentiel avec la prolifération des smartphones, offre des opportunités de personnalisation grâce à la collecte de données. Adapter le contenu pour le mobile, court et percutant, permet une interaction plus pertinente, renforçant la présence de la marque. Marketing mobile : contenu adapté au mobile, personnalisation basée sur la géolocalisation et engagement accru.',
        'trend10_title': '10. Automatisation du marketing : Personnaliser l\'approche client',
        'trend10_description': 'L\'automatisation du marketing transforme l\'interaction client en automatisant les tâches, offrant une expérience personnalisée. Combinée à l\'analyse de données, elle optimise les campagnes marketing, assurant une interaction constante et pertinente avec l\'audience. Avantages de l\'automatisation du marketing : automatisation des tâches, personnalisation avancée et vision intégrée du parcours client.',
        'conclusion_title': 'Conclusion :',
        'conclusion_description': 'En 2024, le marketing digital évolue vers des stratégies plus intelligentes et centrées sur le client. Les entreprises qui intègrent ces tendances dans leurs stratégies auront l\'opportunité de se démarquer et de construire des relations durables avec leurs clients. L\'adaptabilité et l\'innovation restent essentielles pour rester compétitif dans un paysage en constante évolution.',
        // Contact
        'get_in_touch': 'Contactez-nous',
        'elevate_brand': 'Élevez votre marque avec Euklydia',
        'contact_intro': 'N\'hésitez pas à nous contacter <br> nous sommes à un message de distance et prêts à vous aider avec vos besoins!',
        'placeholder_first_name': 'Votre prénom',
        'placeholder_last_name': 'Votre nom de famille',
        'placeholder_email': 'Votre email',
        'placeholder_company': 'Entreprise',
        'placeholder_message': 'Message ici..',
        'send_now': 'Envoyer maintenant',
        'address': 'Adresse',
        'address_details': 'Tunis, Tunisie <br>Paris, France',
        'email': 'E-mail',
        'call_us': 'Appelez-nous',
        'hiring': 'Recrutement',
        'join_team': 'Faites partie de notre équipe',
        'hiring_intro': 'Si vous êtes passionné, talentueux et que vous cherchez un endroit où développer votre carrière, nous voulons vous entendre!',
        'placeholder_field': 'Domaine',

        /// brand creation

        'brand_creation_title': 'Création de marque',
        'current_problem': 'Problème actuel:',
        'problem_title_brand': 'Souffrir pour maintenir la cohérence de votre marque face aux changements rapides du marché?',
        'problem_description_brand': "Assurer la cohérence entre le logo de la marque, les lignes directrices de l'identité et votre client cible nécessite une adaptation continue aux préférences des consommateurs et aux dynamiques du marché en évolution. <br><br> Cela nécessite de garder un œil sur tous les éléments évolutifs du marché, ce qui peut être très compliqué à analyser manuellement en peu de temps.",
        'time': 'Temps',
        'money': 'Argent',
        'brand_identity': 'Identité de la marque',
        'benefits': 'Avantages:',
        'customized_creativity': 'Créativité personnalisée.',
        'increased_audience_resonance': 'Résonance accrue du public.',
        'enhanced_design_alignment': 'Alignement amélioré du design.',
        'streamlined_design_efficiency': 'Efficacité du design rationalisée.',
        'our_solution': 'Notre solution',
        'solution_title': 'Quand les insights de design ciblé rencontrent la créativité personnalisée',
        'solution_description': "Grâce à nos algorithmes d'apprentissage automatique, nous pouvons identifier des modèles et des corrélations entre différents éléments de design, schémas de couleurs et esthétiques visuelles qui résonnent avec les publics cibles. <br><br> Notre équipe créative ajoute une couche supplémentaire de créativité pour rendre chaque client spécial.",
/// tracking

        'brand_tracking': 'Suivi de marque',
        'current_problem': 'Problème actuel:',
        'problem_title': 'Votre stratégie est-elle obscurcie par le mystère du marché ?',
        'problem_description': 'Les solutions analogiques de diagnostic de marque actuelles sont coûteuses tant en termes de budget que de temps, manquant de développement stratégique ciblé et personnalisé, d\'agilité et d\'adaptabilité, entraînant une inflexibilité à retravailler, ainsi qu\'une opacité du marché. <br><br>De plus, les processus de suivi et de diagnostic de marque analogiques sont chronophages et sujets aux changements du marché, rendant potentiellement les insights obsolètes au moment où ils sont terminés.',
        'time': 'Temps',
        'money': 'Argent',
        'benefits': 'Avantages:',
        'actionnable_insights': 'Données exploitables.',
        'enhance_competitive_edge': 'Améliorez votre avantage concurrentiel.',
        'real_time_performance': 'Amélioration de la performance de la marque.',
        'increase_consumer_satisfaction': 'Augmenter la satisfaction.',
        'our_solution': 'Notre solution',
        'solution_title': 'Débloquez les insights pour une stratégie de marque plus pointue',
        'solution_description': 'Grâce à notre algorithme d\'IA développé en interne, nous pouvons analyser de vastes ensembles de données englobant les retours des clients, les interactions sur les réseaux sociaux, le trafic du site web et les données de vente pour effectuer vos diagnostics de marque. <br> <br>Nos algorithmes d\'IA mesurent la notoriété de la marque, le sentiment et l\'analyse concurrentielle, fournissant des insights sur les forces, les faiblesses et les opportunités d\'amélioration. En suivant les métriques d\'engagement des clients, en évaluant la fidélité à la marque et en utilisant des analyses prédictives, <br> <br> nous pouvons personnaliser vos efforts de marketing, optimiser les stratégies et améliorer votre avantage concurrentiel sur le marché, conduisant à une meilleure performance de la marque et à une satisfaction accrue des consommateurs.',
        'capitalize_opportunities': 'Capitaliser sur les opportunités',
        'monitoring_brand': 'Surveillance de la marque',
        'understand_perception': 'Comprendre la perception des consommateurs',

/// social media 

        'social_media_strategy': 'Stratégie réseaux sociaux',
        'current_problem': 'Problème actuel:',
        'problem_title_social_media': 'Frustré par la complexité des réseaux sociaux et la baisse de visibilité?',
        'problem_description_social_media': 'Tout d\'abord, les algorithmes et fonctionnalités en constante évolution des plateformes comme Facebook, Instagram et Twitter rendent difficile pour les marketeurs de maintenir une visibilité et un engagement constants avec leur public cible. <br>De plus, la saturation de contenu sur ces plateformes a entraîné une diminution de la portée organique, obligeant les entreprises à investir davantage dans la publicité payante pour atteindre efficacement leur public cible. En outre, l\'essor du marketing d\'influence a introduit des complexités dans l\'identification des influenceurs authentiques et la mesure du retour sur investissement des partenariats avec les influenceurs. <br><br>De plus, l\'importance croissante de l\'engagement des clients et de la création de communautés exige que les entreprises surveillent et répondent constamment aux commentaires et aux demandes des clients en temps opportun.',
        'revenue': 'Revenu',
        'cost': 'Coût',
        'social_media_repeat': 'Réseaux sociaux',
        'benefits': 'Avantages:',
        'improved_engagement': 'Engagement amélioré.',
        'personalized_communication': 'Communication personnalisée.',
        'increased_visibility': 'Visibilité accrue.',
        'higher_conversion_rates': 'Taux de conversion plus élevés.',
        'our_solution': 'Notre solution',
        'solution_title_social_media': 'Augmentez l\'impact de vos réseaux sociaux avec une personnalisation pilotée par l\'IA',
        'solution_description_social_media': 'Notre IA développée en interne renforce l\'engagement des consommateurs avec les réseaux sociaux en analysant les interactions des utilisateurs avec les publicités, en affinant les stratégies et en améliorant l\'expérience utilisateur globale grâce à des messages personnalisés et à une utilisation optimisée des publicités. <br><br>L\'analyse de grandes quantités de données telles que les copies d\'annonces, les commentaires, les types de publications, le vocabulaire et les interactions nous permet de créer des messages ciblés permettant au client de s\'identifier, ce qui augmente notre visibilité et notre conversion sur les plateformes meta et LinkedIn.',

        // content creation
        'content_creation': 'Création de contenu',
        'current_problem': 'Problème actuel:',
        'problem_title_content_creation': 'Frustré par la complexité de la création de contenu et l\'impact décroissant?',
        'problem_description_content_creation': 'Tout d\'abord, les normes et tendances en constante évolution de la création de contenu rendent difficile pour les créateurs de produire constamment du contenu qui résonne avec leur public. La nécessité de rester à jour avec les derniers formats, outils et plateformes peut être écrasante. <br>De plus, la saturation de contenu à travers divers médias a entraîné une baisse de l\'engagement du public. Cela rend plus difficile pour les créateurs de se démarquer et de capter l\'attention de leur public cible sans investir massivement dans le marketing et la promotion. <br>En outre, l\'émergence de nouveaux types de contenu, tels que les vidéos courtes et les médias interactifs, introduit des complexités dans la stratégie et la production de contenu. Les créateurs doivent continuellement innover et s\'adapter aux nouveaux formats pour rester pertinents.',
        'time': 'Temps',
        'money': 'Argent',
        'content_creation_repeat': 'Création de contenu',
        'benefits': 'Avantages:',
        'streamlined_content_strategy': 'Stratégie de contenu rationalisée.',
        'efficient_production_process': 'Processus de production efficace.',
        'audience_centric_messaging': 'Messages centrés sur le public.',
        'increased_content_impact': 'Impact du contenu accru.',
        'our_solution': 'Notre solution',
        'solution_title_content_creation': 'Révolutionnez la création de contenu avec une innovation pilotée par l\'IA',
        'solution_description_content_creation': 'Notre IA développée en interne transforme la création de contenu en analysant les interactions des utilisateurs, en optimisant les stratégies et en améliorant l\'expérience utilisateur globale grâce à un contenu personnalisé et à des processus de production rationalisés. <br><br>En analysant de vastes quantités de données telles que le type de contenu, les commentaires, le vocabulaire et les métriques d\'engagement, nous créons un contenu ciblé qui résonne avec votre public. Cette approche augmente la visibilité et l\'engagement sur diverses plateformes, conduisant à des conversions accrues et à une présence en ligne plus forte. <br><br>Grâce aux insights pilotés par l\'IA, nous vous aidons à anticiper les tendances, à vous adapter aux normes changeantes et à produire en continu du contenu de haute qualité et percutant.',

        // web creation
        'web_creation': 'Création web',
        'current_problem': 'Problème actuel:',
        'problem_title_web_creation': 'Visiteurs perdus et faibles conversions : La conception de votre site web est-elle en cause ?',
        'problem_description_web_creation': 'Tout d\'abord, un contenu peu engageant peut décourager les utilisateurs d\'explorer davantage, entraînant des taux de rebond élevés. <br><br> Ensuite, une hiérarchie de l\'information médiocre peut rendre les utilisateurs perdus si des détails cruciaux ne sont pas mis en évidence ou facilement accessibles. De plus, des formulaires complexes peuvent dissuader les utilisateurs de fournir des informations, réduisant ainsi les conversions. <br><br>De plus, les sites web manquant d\'optimisation pour les moteurs de recherche ont du mal à attirer du trafic organique, limitant ainsi la visibilité et l\'efficacité.',
        'connecting_with_target_customers': 'Se connecter avec vos clients cibles',
        'benefits': 'Avantages:',
        'seo_optimization': 'Optimisation SEO',
        'enhanced_navigation': 'Navigation améliorée',
        'higher_conversion_rates': 'Taux de conversion plus élevés',
        'increased_engagement': 'Engagement accru',
        'our_solution': 'Notre solution',
        'solution_title_web_creation': 'Améliorez l\'expérience utilisateur et le SEO de votre site web avec une analyse avancée de l\'IA et du NLP',
        'solution_description_web_creation': 'En analysant le comportement des utilisateurs avec l\'IA sur le site web, nous pouvons identifier les schémas de navigation courants et recommander la navigation la plus intuitive et efficace. <br><br>LLM et NLP peuvent aider à optimiser le contenu et la structure du site pour améliorer son classement dans les moteurs de recherche en identifiant les mots-clés pertinents, en optimisant les balises méta et en recommandant des améliorations. <br><br>Ce processus est connu sous le nom d\'optimisation pour les moteurs de recherche (SEO).'
    }
};


function translateContent(lang) {
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang] && translations[lang][key]) {
            element.innerHTML = translations[lang][key];
        } else {
            console.warn(`No translation found for ${key} in ${lang}`);
        }
    });
}

function setLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);
    translateContent(lang);
}

document.querySelectorAll('.lang').forEach(button => {
    button.addEventListener('click', event => {
        event.preventDefault();
        const lang = event.target.closest('.lang').getAttribute('data-lang');
        setLanguage(lang);
    });
});

const initialLanguage = localStorage.getItem('selectedLanguage') || 'en';
setLanguage(initialLanguage);
